### ISSUE TITLE
Feature suggestion: borders

### ISSUE THREAD

**Issue by hightowe** [the-allanc/minty-color-titles#2]
First, this is a great piece of work to make Mint 21.1 more usable. Thanks!

I added this to my css, to better match the theme that I was using in Mint 19.3 which provided a thin, theme-colored border on the active window, which I find to be very helpful, and I thought that you may like it:

~~~
decoration:not(:backdrop) {
  border: 1px solid @active_window_bg_color;
  background: gray;
}
decoration {
  border: 1px solid gray;
  background: gray;
}
~~~

**Comment by gessel** [comment]
This is just awesome, it vastly improves the usability of dark themes for me.  The interwebs are full of requests to either add a border around windows and active window title bar differentiation to themes or remove it.  This is obviously for those of us that want the former and I'm using it with Minty dark on one box and Yaru dark on an Ubuntu 22.04 box and both work great.  

With borders, and active window title bar differentiation from background windows I can quickly find the menu bar I want and easily see the bounds of windows.  For me, this is a vast improvement. 

I spent a lot of time searching for css fixes and using GTK+ inspector and found this.    THANKS!!!

**Comment by frank-bg** [comment]
hi! I like this a lot, but there is a caveat

the border of menus and contextual menus is also altered

![Image](https://github.com/user-attachments/assets/5b502322-59c0-4827-9f0f-c7ef6bdc06a9)

tried the following, no success

```css
window > decoration:not(:backdrop) {
    border: 3px solid @active_window_bg_color;
    background: gray;
}

window > decoration {
    border: 3px solid @inactive_window_bg_color;
    background: gray;
}
```

is there a solution?

**Comment by hightowe** [comment]
@frank-bg  - I've not seen the problem that you demonstrate in your comment, and I don't have an answer for you...

A little Google searching turned up this extension, which may be worth a try: https://extensions.gnome.org/extension/4699/highlight-focus/

**Comment by frank-bg** [comment]
Hi, I chose to use a border-left style for the window decoration. I find it visually appealing. 

```css
window > decoration:not(:backdrop) {
    border-left: 3px solid @active_window_bg_color;
    background: gray;
}

window > decoration {
    border-left: 3px solid @inactive_window_bg_color;
    background: gray;
}
```

![Image](https://github.com/user-attachments/assets/d7ed5da4-14c9-4e81-ab21-2fcf8fa9641f)
